spring.application.name=backend

# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-gentle-salad-axlpaaws-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DbklfsryVi80
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081